export {default as GuestPage} from './HomepageGuest/index.jsx'
export {default as HomePage} from './HomePage/index.jsx'
export {default as Story} from './Story/index.jsx'
export {default as ProfilesPage} from './ProfilesPage/index.jsx'
export {default as SignIn} from './SigninPage/index.jsx'
export {default as SignUp} from './SignUpPage/index.jsx'